{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "distributed-system.fullname" . }}-default-deny
spec:
  podSelector:
    matchLabels:
      {{- include "distributed-system.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "distributed-system.fullname" . }}-allowed
spec:
  podSelector:
    matchLabels:
      {{- include "distributed-system.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "distributed-system.selectorLabels" . | nindent 14 }}
      ports:
        - {protocol: TCP, port: {{ .Values.service.protocolPort }}}
    - from:
        - namespaceSelector: {}
      ports:
        - {protocol: TCP, port: {{ .Values.service.observabilityPort }}}
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "distributed-system.selectorLabels" . | nindent 14 }}
      ports:
        - {protocol: TCP, port: {{ .Values.service.protocolPort }}}
    - to:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.dnsNamespaceSelector | nindent 14 }}
      ports:
        - {protocol: UDP, port: 53}
        - {protocol: TCP, port: 53}
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: etcd
      ports:
        - {protocol: TCP, port: 2379}
    - ports:
        - {protocol: TCP, port: 4318}
{{- end }}
