{{- include "distributed-system.validate" . }}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "distributed-system.serviceAccountName" . }}
  labels:
    {{- include "distributed-system.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
