apiVersion: v1
kind: Service
metadata:
  name: {{ include "distributed-system.fullname" . }}-headless
  labels:
    {{- include "distributed-system.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "distributed-system.selectorLabels" . | nindent 4 }}
  ports:
    - name: protocol
      port: {{ .Values.service.protocolPort }}
      targetPort: protocol
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "distributed-system.fullname" . }}-metrics
  labels:
    {{- include "distributed-system.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "distributed-system.selectorLabels" . | nindent 4 }}
  ports:
    - name: observability
      port: {{ .Values.service.observabilityPort }}
      targetPort: observability
