{{- if and .Values.tls.enabled (or .Values.tls.caCrt .Values.tls.serverCrt) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "distributed-system.fullname" . }}-tls
  labels:
    {{- include "distributed-system.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Values.tls.caCrt | default "" | b64enc }}
  server.crt: {{ .Values.tls.serverCrt | default "" | b64enc }}
  server.key: {{ .Values.tls.serverKey | default "" | b64enc }}
{{- end }}