apiVersion: v1
kind: Service
metadata:
  name: {{ include "distributed-system.fullname" . }}
  labels:
    {{- include "distributed-system.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "distributed-system.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics