apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}-headless
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}
  ports:
    - {name: client, port: {{ .Values.service.clientPort }}, targetPort: client}
    - {name: peer, port: {{ .Values.service.peerPort }}, targetPort: peer}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}
  ports:
    - {name: client, port: {{ .Values.service.clientPort }}, targetPort: client}
