apiVersion: v1
kind: Service
metadata:
  name: dist-sys
  namespace: distributed-system
  labels:
    app: distributed-system
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: distributed-system
  ports:
    - name: grpc
      port: 8000
      targetPort: 8000
    - name: metrics
      port: 9090
      targetPort: 9090